# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1614cb181de96b9b364b9c7976afb37f0c579484c940660431ef1627a7ee89d60c043acde0f238a80d7e70f88728a051d54620566eb871ec72c6abd853d0252

test:
  secret_key_base: 77319b552aba6852d89d3ba081ba14ce12ccd8db741a3a5c748b335334c61bcddef0867f1abd1496ac1746490145df46c11c7fcd6d2970ddcc642026181d3263

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
